# Generated by Django 3.2.13 on 2022-05-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("plot", models.TextField()),
                ("year", models.PositiveIntegerField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (0, "NR - Not Rate"),
                            (1, "G - General Audiences"),
                            (2, "PG – Parental Guidance Suggested"),
                            (3, "PG-13 – Parents Strongly Cautioned"),
                            (4, "R – Restricted"),
                            (5, "NC-17 – Adults Only"),
                        ],
                        default=0,
                    ),
                ),
                ("runtime", models.PositiveIntegerField()),
                ("website", models.URLField(blank=True)),
                (
                    "actors",
                    models.ManyToManyField(
                        blank=True, related_name="acting_credits", to="actors.Person"
                    ),
                ),
            ],
        ),
    ]
